include: package:lint/strict.yaml

analyzer:
  plugins:
    - dart_code_metrics
  strong-mode:
    implicit-casts: true
  errors:
    avoid_web_libraries_in_flutter: error
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "test/.test_coverage.dart"
    - "bin/cache/**"



linter:
  rules:
    close_sinks: false
    file_names: false
    prefer_relative_imports: true
    always_use_package_imports: false
    avoid_classes_with_only_static_members: false
    invalid_annotation_target: false
    prefer-immediate-return: true
    avoid_unused_constructor_parameters: false

dart_code_metrics:
  rules:
    - prefer-single-widget-per-file:
        ignore-private-widgets: true
    - member-ordering:
        order:
          - constructors
          - public-fields
          - private-fields
          - public-getters
          - private-getters
          - public-setters
          - private-setters
          - public-methods
          - private-methods
    - prefer-moving-to-variable:
        allowed-duplicated-chains: 3
    - prefer-extracting-callbacks:
        allowed-line-count: 3
    - prefer-match-file-name
    - prefer-immediate-return
    - prefer-correct-edge-insets-constructor
    - prefer-const-border-radius
    - always-remove-listener
    - avoid-shrink-wrap-in-lists
    - prefer-commenting-analyzer-ignores

